# Generated by Django 4.1.4 on 2023-01-29 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='gallery',
        ),
        migrations.AddField(
            model_name='shelter',
            name='email',
            field=models.EmailField(blank=True, help_text='Укажите почту для связи с приютом', max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Укажите телефон приюта', max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,11}$')], verbose_name='Телефон приюта'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Загрузите фото профиля', null=True, upload_to='', verbose_name='Фото профиля'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='web_site',
            field=models.URLField(blank=True, help_text='Укажите сайт приюта', verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='working_hours',
            field=models.CharField(default='10:00 - 18:00', help_text='Укажите режим работы в формате "hh:mm - hh:mm"', max_length=13, verbose_name='Режим работы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shelter',
            name='address',
            field=models.TextField(blank=True, default='example', help_text='Укажите адрес приюта', verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shelter',
            name='name',
            field=models.CharField(help_text='Введите название приюта', max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
