# Generated by Django 4.1.4 on 2023-01-29 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelters', '0002_remove_shelter_gallery_shelter_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Приют проверен'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='shelter', to=settings.AUTH_USER_MODEL, verbose_name='Владелец приюта'),
            preserve_default=False,
        ),
    ]
