# Generated by Django 4.1.4 on 2023-02-05 12:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelters', '0004_pet_is_adopted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shelter', to=settings.AUTH_USER_MODEL, verbose_name='Владелец приюта'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Укажите телефон приюта', max_length=12, validators=[django.core.validators.RegexValidator(regex='12345')], verbose_name='Телефон приюта'),
        ),
    ]
