# Generated by Django 4.1.4 on 2023-02-06 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0005_alter_shelter_lat_alter_shelter_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Укажите телефон приюта', max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+\\d{11}$')], verbose_name='Телефон приюта'),
        ),
    ]
