# Generated by Django 4.1.4 on 2023-02-15 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0006_alter_shelter_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='shelter',
            name='legal_owner_name',
            field=models.CharField(default='vasia', help_text='Укажите ФИО юридического владельца приюта', max_length=50, verbose_name='ФИО владельца приюта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='ok_page',
            field=models.URLField(blank=True, help_text='Укажите адрес группы в Однокласниках', verbose_name='Группа в Однокласника'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='telegram',
            field=models.URLField(blank=True, help_text='Укажите адрес телеграм канала', verbose_name='Телеграм канал'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='tin',
            field=models.CharField(default='1234567890', help_text='Укажите номер ИНН', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')], verbose_name='ИНН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='vk_page',
            field=models.URLField(blank=True, help_text='Укажимте адрес группы в ВК', verbose_name='Группа в ВК'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='working_from_hour',
            field=models.TimeField(default='10', help_text='Укажите время начала работы приюта', verbose_name='Время начала работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='working_to_hour',
            field=models.TimeField(default='13', help_text='Укажите время окончания работы приюта', verbose_name='Время окончания работы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shelter',
            name='description',
            field=models.TextField(help_text='Добавьте описание приюта', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='email',
            field=models.EmailField(help_text='Укажите почту для связи с приютом', max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='phone_number',
            field=models.CharField(help_text='Укажите телефон приюта', max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+\\d{11}$')], verbose_name='Телефон приюта'),
        ),
    ]
