# Generated by Django 4.1.4 on 2023-02-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0007_remove_shelter_working_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='address',
            field=models.TextField(blank=True, help_text='Укажите адрес приюта', max_length=256, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='email',
            field=models.EmailField(help_text='Укажите почту для связи с приютом', max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
