# Generated by Django 4.1.4 on 2023-02-15 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0008_alter_shelter_address_alter_shelter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='ok_page',
            field=models.URLField(blank=True, help_text='Укажите адрес группы в Однокласниках', validators=[django.core.validators.RegexValidator(regex='^https://ok.ru/')], verbose_name='Группа в Однокласника'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='telegram',
            field=models.URLField(blank=True, help_text='Укажите адрес телеграм канала', validators=[django.core.validators.RegexValidator(regex='^https://t.me/')], verbose_name='Телеграм канал'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='vk_page',
            field=models.URLField(blank=True, help_text='Укажимте адрес группы в ВК', validators=[django.core.validators.RegexValidator(regex='^https://vk.com/')], verbose_name='Группа в ВК'),
        ),
    ]
