# Generated by Django 4.1.4 on 2023-02-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0009_alter_shelter_ok_page_alter_shelter_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='address',
            field=models.TextField(blank=True, help_text='Укажите адрес приюта', max_length=100, verbose_name='Адрес'),
        ),
    ]
