# Generated by Django 4.1.4 on 2023-02-27 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0010_alter_shelter_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Вид животного')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Вид животного',
                'verbose_name_plural': 'Виды животных',
            },
        ),
        migrations.AddField(
            model_name='shelter',
            name='animal_types',
            field=models.ManyToManyField(related_name='shelters', to='shelters.animaltype', verbose_name='Виды животных'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='animal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='shelters.animaltype', verbose_name='Вид животного'),
        ),
    ]
