# Generated by Django 4.1.4 on 2023-03-04 16:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0012_pet_birth_date_pet_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='about',
            field=models.TextField(max_length=500, verbose_name='Описание животного'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='shelters.shelter', verbose_name='Приют'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='address',
            field=models.TextField(blank=True, max_length=100, verbose_name='Адрес приюта'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание приюта'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='legal_owner_name',
            field=models.CharField(max_length=50, verbose_name='ФИО владельца приюта'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название приюта'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='tin',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')], verbose_name='ИНН'),
        ),
    ]
