# Generated by Django 4.1.4 on 2023-03-04 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0013_alter_pet_about_alter_pet_shelter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='email',
            field=models.EmailField(max_length=256, unique=True, verbose_name='Email приюта'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Логотип приюта'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='ok_page',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='^https://ok.ru/')], verbose_name='Группа в Однокласниках'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+\\d{11}$')], verbose_name='Телефон приюта'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='telegram',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='^https://t.me/')], verbose_name='Телеграм канал'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='vk_page',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='^https://vk.com/')], verbose_name='Группа в ВК'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='web_site',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='working_from_hour',
            field=models.TimeField(verbose_name='Время начала работы'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='working_to_hour',
            field=models.TimeField(verbose_name='Время окончания работы'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Краткое описание задачи'),
        ),
    ]
