# Generated by Django 4.1.4 on 2023-06-14 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0014_alter_shelter_email_alter_shelter_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='shelters.shelter', verbose_name='Приют'),
        ),
    ]
