# Generated by Django 4.1.4 on 2023-06-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0015_alter_pet_shelter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaltype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='animal_type',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='animal_types',
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='slug',
            field=models.SlugField(max_length=20, primary_key=True, serialize=False, verbose_name='Слаг'),
        ),
    ]
