# Generated by Django 4.1.4 on 2023-06-15 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0016_remove_animaltype_id_remove_pet_animal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='animal_type',
            field=models.ForeignKey(default='cat', on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='shelters.animaltype', verbose_name='Вид животного'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='animal_types',
            field=models.ManyToManyField(related_name='shelters', to='shelters.animaltype', verbose_name='Виды животных'),
        ),
    ]
