# Generated by Django 4.1.4 on 2023-07-30 20:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('shelters', '0017_pet_animal_type_shelter_animal_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='photo',
        ),
        migrations.AddField(
            model_name='pet',
            name='admission_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата поступления в приют'),
        ),
        migrations.AddField(
            model_name='pet',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_related', related_query_name='%(class)s', to='gallery.image', verbose_name='Галерея животного'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('male', 'самец'), ('female', 'самка'), ('other', 'другое')], default='other', max_length=6, verbose_name='Пол животного'),
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('slug', models.SlugField(max_length=20, primary_key=True, serialize=False, verbose_name='Слаг')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Порода животного')),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breeds', to='shelters.animaltype', verbose_name='Вид животного')),
            ],
            options={
                'verbose_name': 'Порода животного',
                'verbose_name_plural': 'Породы животных',
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='shelters.breed', verbose_name='Порода животного'),
            preserve_default=False,
        ),
    ]
