# Generated by Django 4.1.4 on 2023-08-06 22:32

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('shelters', '0018_alter_task_options_remove_task_is_emergency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='photo',
        ),
        migrations.AddField(
            model_name='pet',
            name='admission_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата поступления в приют'),
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Порода животного'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_related', related_query_name='%(class)s', to='gallery.image', verbose_name='Галерея животного'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('male', 'самец'), ('female', 'самка'), ('other', 'другое')], default='other', max_length=6, verbose_name='Пол животного'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='ok_page',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(regex='^https://ok.ru/')], verbose_name='Группа в Одноклассниках'),
        ),
    ]
