# Generated by Django 4.1.4 on 2023-09-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0019_remove_pet_photo_pet_admission_date_pet_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
