# Generated by Django 4.1.4 on 2022-12-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Вопрос для FAQ', max_length=200, verbose_name='Заголовок вопроса')),
                ('answer', models.TextField(help_text='Напишите четкий полезный ответ', verbose_name='Ответ на вопрос')),
            ],
            options={
                'verbose_name_plural': 'Ответы на частые вопросы',
                'ordering': ('question',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Выберите изображение для загрузки', upload_to='temporary/', verbose_name='Изображение')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(help_text='Введите заголовок новости, максимум 50 символов', max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(help_text='Введите текст поста', verbose_name='Текст новости')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='OwnVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='Введите название должности', max_length=30, verbose_name='Доложность')),
                ('description', models.TextField(help_text='Опишите подробности вакансии', verbose_name='Описание')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Вакансия закрыта')),
            ],
            options={
                'verbose_name': 'Своя Вакансия',
                'verbose_name_plural': 'Свои Вакансии',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='StaticInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(help_text='Расскажите о миссии, команде', verbose_name='О компании')),
                ('portfolio', models.TextField(help_text='Разместите портфолио команды', verbose_name='Портфолио')),
                ('rewards', models.TextField(help_text='Разместите информацию о наградах', verbose_name='Награды')),
                ('contacts', models.TextField(help_text='Укажите контакты', verbose_name='Контакты')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='Введите название должности', max_length=30, verbose_name='Доложность')),
                ('description', models.TextField(help_text='Опишите подробности вакансии', verbose_name='Описание')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Вакансия закрыта')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ('-pub_date',),
            },
        ),
    ]
