# Generated by Django 4.1.4 on 2023-01-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_rename_vacancy_sheltervacancy_delete_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Выберите дополнительное фото', upload_to='', verbose_name='Фото 1'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Выберите дополнительное фото', upload_to='', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Выберите дополнительное фото', upload_to='', verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='news',
            name='profile_image',
            field=models.ImageField(default='192443-13421807.jpg', help_text='Выберите основное изображение', upload_to='', verbose_name='Основное изображение'),
            preserve_default=False,
        ),
    ]
