# Generated by Django 4.1.4 on 2023-01-29 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0004_pet_is_adopted'),
        ('info', '0005_helparticle_news_on_main_news_shelter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='shelter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='shelters.shelter', verbose_name='Новость от приюта'),
        ),
    ]
