# Generated by Django 4.1.4 on 2023-02-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_news_shelter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helparticle',
            name='text',
            field=models.TextField(help_text='Введите текст новости', max_length=2000, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(help_text='Введите текст новости', max_length=2000, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='ownvacancy',
            name='description',
            field=models.TextField(help_text='Опишите подробности вакансии', max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sheltervacancy',
            name='description',
            field=models.TextField(help_text='Опишите подробности вакансии', max_length=500, verbose_name='Описание'),
        ),
    ]
