# Generated by Django 4.1.4 on 2023-03-04 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0012_pet_birth_date_pet_sex'),
        ('info', '0010_alter_vacancy_shelter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='position',
            field=models.CharField(max_length=30, verbose_name='Доложность'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='shelter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='shelters.shelter', verbose_name='Вакансия в приюте'),
        ),
    ]
