# Generated by Django 4.1.4 on 2023-03-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_vacancy_salary_vacancy_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=500, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=200, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='helparticle',
            name='header',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='helparticle',
            name='profile_image',
            field=models.ImageField(upload_to='', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='helparticle',
            name='source',
            field=models.URLField(verbose_name='url адрес источника'),
        ),
        migrations.AlterField(
            model_name='helparticle',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='header',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='news',
            name='profile_image',
            field=models.ImageField(upload_to='', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='about_us',
            field=models.TextField(verbose_name='О компании'),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='contacts',
            field=models.TextField(verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='portfolio',
            field=models.TextField(verbose_name='Портфолио'),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='rewards',
            field=models.TextField(verbose_name='Награды'),
        ),
    ]
