# Generated by Django 4.1.4 on 2023-06-04 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_alter_faq_answer_alter_faq_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('slug', models.SlugField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('slug', models.SlugField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_ndfl',
            field=models.BooleanField(default=False, verbose_name='НДФЛ'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.PositiveIntegerField(verbose_name='Оплата'),
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='schedule',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='education',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='info.education', verbose_name='Образование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='schedule',
            field=models.ManyToManyField(related_name='vacancies', to='info.schedule', verbose_name='График работы'),
        ),
    ]
