# Generated by Django 4.1.4 on 2023-07-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('info', '0014_education_schedule_vacancy_is_ndfl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_3',
        ),
        migrations.AddField(
            model_name='helparticle',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_related', related_query_name='%(class)s', to='gallery.image', verbose_name='Галерея'),
        ),
        migrations.AddField(
            model_name='news',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_related', related_query_name='%(class)s', to='gallery.image', verbose_name='Галерея'),
        ),
    ]
