# Generated by Django 4.1.4 on 2023-08-06 21:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '__first__'),
        ('info', '0014_education_schedule_vacancy_is_ndfl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_3',
        ),
        migrations.AddField(
            model_name='helparticle',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_related', related_query_name='%(class)s', to='gallery.image', verbose_name='Галерея'),
        ),
        migrations.AddField(
            model_name='news',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_related', related_query_name='%(class)s', to='gallery.image', verbose_name='Галерея'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_ndfl',
            field=models.CharField(choices=[('ndfl', 'с НДФЛ'), ('no_ndfl', 'На руки')], default='ndfl', max_length=7, verbose_name='Тип оплаты'),
        ),
    ]
