# Generated by Django 4.1.4 on 2023-06-11 21:04

from django.db import migrations, models
import info.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_education_schedule_vacancy_is_ndfl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', validators=[info.models.validate_image_size], verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_3',
        ),
        migrations.AddField(
            model_name='helparticle',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_related', related_query_name='%(class)s', to='info.image', verbose_name='Галерея'),
        ),
        migrations.AddField(
            model_name='news',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_related', related_query_name='%(class)s', to='info.image', verbose_name='Галерея'),
        ),
    ]
