# Generated by Django 4.1.4 on 2023-08-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_image_remove_news_image_1_remove_news_image_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='names',
            new_name='name',
        ),
    ]
