# Generated by Django 4.1.4 on 2023-08-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_rename_names_schedule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='is_ndfl',
            field=models.CharField(choices=[('ndfl', 'с НДФЛ'), ('no_ndfl', 'На руки')], default='ndfl', max_length=7, verbose_name='Тип оплаты'),
        ),
    ]
