# Generated by Django 4.1.4 on 2023-11-09 15:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelters', '0020_alter_pet_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='YookassaOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='Токен')),
                ('expires_at', models.DateTimeField(verbose_name='Дата истекания')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yookassa_token', to='shelters.shelter', verbose_name='Приют')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Сумма')),
                ('is_successful', models.BooleanField(default=False, verbose_name='Завершен успешно')),
                ('external_id', models.CharField(max_length=255, verbose_name='Внешний ID платежа')),
                ('shelter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='shelters.shelter', verbose_name='Приют')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
