# Generated by Django 4.1.4 on 2023-11-10 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Сумма'),
        ),
    ]
