# Generated by Django 4.1.4 on 2023-11-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_alter_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="external_id",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Внешний ID платежа"
            ),
        ),
    ]
