# Generated by Django 4.1.4 on 2023-11-19 16:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shelters", "0020_alter_pet_birth_date"),
        ("payments", "0004_alter_payment_amount"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Payment",
            new_name="Donation",
        ),
    ]
