# Generated by Django 4.1.4 on 2023-11-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_rename_payment_donation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yookassaoauthtoken",
            name="token",
            field=models.CharField(max_length=512, verbose_name="Токен"),
        ),
    ]
