# Generated by Django 4.1.4 on 2024-02-11 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shelters", "0020_alter_pet_birth_date"),
        ("payments", "0006_alter_yookassaoauthtoken_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yookassaoauthtoken",
            name="expires_at",
            field=models.DateTimeField(verbose_name="Дата истечения"),
        ),
        migrations.AlterField(
            model_name="yookassaoauthtoken",
            name="shelter",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="yookassa_token",
                to="shelters.shelter",
                verbose_name="Приют",
            ),
        ),
    ]
