# Generated by Django 4.1.4 on 2024-02-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0007_alter_yookassaoauthtoken_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donation",
            options={
                "verbose_name": "Пожертвование",
                "verbose_name_plural": "Пожертвования",
            },
        ),
        migrations.AlterModelOptions(
            name="yookassaoauthtoken",
            options={
                "verbose_name": "OAuth токен приюта",
                "verbose_name_plural": "OAuth токены приютов",
            },
        ),
        migrations.AddField(
            model_name="donation",
            name="created_at",
            field=models.DateTimeField(
                default=None, verbose_name="Дата и время создания платежа"
            ),
            preserve_default=False,
        ),
    ]
