# Generated by Django 4.1.4 on 2023-03-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Введите имя пользователя', max_length=150, verbose_name='Имя пользователя'),
        ),
    ]
