# Generated by Django 4.1.4 on 2023-06-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpet',
            name='want_to_adopt',
        ),
        migrations.RemoveField(
            model_name='usershelter',
            name='is_volunteer',
        ),
    ]
