# Generated by Django 4.1.4 on 2023-06-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userpet_want_to_adopt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='donations_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Сумма пожертвований'),
        ),
    ]
